### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by MatthiasLohr**
This is a first draft of GitHub actions utilization. I never worked with GitHub actions before, so I'm not completely sure about the process of releasing/uploading artifacts to PyPI.

### CODE REVIEW

**Comment by cburgdorf** [comment]
Hey @MatthiasLohr, that looks good! Thanks for setting it up. I can probably take it from here to  wire up the rest of the pipeline that pushes the releases to pypi. But actually, I'll need your help here @davesque. I don't have administrative rights in this repository to setup secrets which we need to do to push into PyPi.

I see three possible ways forward and all of them are fine to me:

1. You take it from here and wire up the rest to push releases to pypi. You remain the only one with administrative rights.

2. You grant me administrative rights and I'll set it up (creating a new pypi token from my username to be used exclusively for this project)

3. We fork this into an official ethereum repository and take care of the rest.

1, 2 and 3 are ordered from most hassle on your end to most hassle on my end :joy: What would you prefer?

**Comment by MatthiasLohr** [comment]
I know I'm not eligible to vote... but I vote for option 3! (also considering the comment from @fubuloubu in #2). Btw, instead of forking, you could also "transfer" it to Ethereum group - so it would look more like the "main" repository. I usually check twice before I create a pull request - and mostly tend to open it again the "fork head" instead of some forks.

**Comment by cburgdorf** [comment]
Yeah, I can see why option 3 might be compelling but I also don't want to "steal" it if David wants to continue to maintain it. And thanks for the *transfer* suggestion, makes sense :+1:

**Comment by MatthiasLohr** [comment]
Any update on this...?

**Comment by cburgdorf** [comment]
@davesque Would you be ok to transfer ownership to the EF? I'm going to also send you an email just in case you aren't observing these messages here.

**Comment by cburgdorf** [comment]
>Hey, yeah I would be happy to transfer ownership.

Thanks, happy to hear!

It sounds like that you would need to have rights to create repositories in the EF organization to be allowed to make the transfer. So maybe someone from devops  needs to be added as an owner to this repo first.

image

The transfer has the blessing from @pipermerriam. I'll make a post in the EFs devops channel to see who can assist us with the transfer.

**Comment by MatthiasLohr** [comment]
Hey, any progress here?

**Comment by cburgdorf** [comment]
>Hey, any progress here?

Sorry, holdup were on my part. I missed the response from devops.

@davesque do you mind making @Aldekein from devops an admin on this repo so he can initiate the transfer?

**Comment by davesque** [comment]
@cburgdorf Alright, there was no option to make @Aldekein an admin since this is a personal repo.  So I just transferred the repo to him.  I think he can finish the process of transferring it to the EF.

**Comment by cburgdorf** [comment]
Thanks, that should work :+1:

**Comment by cburgdorf** [comment]
Migration worked, thanks! I still need to get access to the management of the environment variables exposed to Github Actions to complete the process but we should soon be able to wrap this up :)

**Comment by MatthiasLohr** [comment]
Hi, sorry to bother you again, but I really would like to see that fixed... ;)

**Comment by cburgdorf** [comment]
Yep, me too. I pinged devops again today because I'm still lacking the administrative rights to setup the pypi token. I'll keep pushing this week :)

**Comment by Aldekein** [comment]
@cburgdorf now you have administrative rights for the blake2b-py repo. Sorry for the delay!

**Comment by cburgdorf** [comment]
@Aldekein Thanks, everything is working fine now.

@MatthiasLohr This now landed as part of #4 

I also cut a new version `0.1.4` wich also covers Python 3.9. You can [see the packages on pypi](https://pypi.org/project/blake2b-py/0.1.4/#files). Thanks for pushing this forward :)

**Comment by MatthiasLohr** [comment]
Finally!!! Thanks :) And sorry for pushing so hard ;)

**Pull request closed without merging**
